name: master_detail_flow
description: A package that provides a simple master-detail-flow with material 3
version: 2.5.0
repository: https://github.com/2-5-perceivers/flutter-master-detail-flow

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
